#!/bin/bash

if [ "$1" = "-serial" ]; then
	[ -f console.log ] && mv console.log console-last.log
	SERIAL_APPEND="console=\"ttyS0,115200\""
	SERIAL="-serial file:console.log"
fi

CONSOLE="console=tty1 highres=off $SERIAL_APPEND"
ROOT="root=/dev/hda rw --no-log"

set -x

qemu-system-x86_64 -smp 2 -cpu host -m 6G \
    -hda ./linuxdisk.raw -hdb ./ftfs-southbound.raw \
    -kernel ../arch/x86/boot/bzImage \
	-append "$CONSOLE $ROOT" \
	-curses -s $SERIAL \
	-enable-kvm 
