// This file is automatically generated.
// Please run pthread_union_check.py
// when making kernel config changes

#ifndef FTFS_KERN_CONFIG_H
#define FTFS_KERN_CONFIG_H


//#define CONFIG_LOCK_STAT
//#define CONFIG_GENERIC_LOCKBREAK
#define CONFIG_DEBUG_SPINLOCK
//#define CONFIG_DEBUG_LOCK_ALLOC
#define CONFIG_DEBUG_MUTEXES
#define CONFIG_SMP
//#define CONFIG_MUTEX_SPIN_ON_OWNER
//#define CONFIG_RWSEM_GENERIC_SPINLOCK


#endif //FTFS_KERN_CONFIG_H
