vagrant_root = File.dirname(__FILE__)

Vagrant.configure("2") do |config|
  config.vm.box = "betrfs-dev"
  config.vm.define "betrfs-dev"
  config.vm.synced_folder "../", "/vagrant", type: "nfs"
  config.vm.provider "libvirt" do |libvirt|
    libvirt.qemuargs :value => "-serial"
    libvirt.qemuargs :value => "file:" + vagrant_root + "/console.out"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install -y schroot debian-keyring
  SHELL

end
